name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.9, '3.10', '3.11', '3.12']
    services:
      rqlite:
        image: rqlite/rqlite
        options: -p4001:4001
    steps:
      - name: Setup Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - name: Fetch httppubsubserver
        uses: actions/checkout@v2
      - name: Generic python setup
        run: |
          python -m pip install --upgrade pip
      - name: Installing dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Lint httppubsubserver with black
        run: |
          python -m black --check src/httppubsubserver
